language: go

go:
    - 1.13.x

before_install:
    - go get github.com/mitchellh/gox
    - go get

install:
    - gox 

script:
    - ls -l|grep -i goccert

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file:
        - GoCCert_*
    skip_cleanup: true
    on:
        go: 1.13.x
        tags: false
