language: go

go:
    - 1.13.x

before_install:
    - export GIT_COMMIT=$(git rev-list -1 HEAD) 
    - go get github.com/mitchellh/gox
    - go get

install:
    - gox -ldflags="-X main.version=$(git tag) -X main.commit=$(git rev-list -1 HEAD)"

script:
    - ls -l|grep -i goccert

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file:
        - GoCCert_*
    skip_cleanup: true
    on:
        go: 1.13.x
        tags: true
